backend:
  name: github
  repo: kkosma/netlify-nuxt-test
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "history" # Used in routes, e.g., /admin/collections/blog
    label: "History" # Used in the UI
    folder: "content/history" # The path to the folder where the documents are stored
    filter: {field: "layout", value: "vertical-halves"}
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "research" # Used in routes, e.g., /admin/collections/blog
    label: "Research" # Used in the UI
    folder: "content/research" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Gallery" 
        name: "galleryImages"
        widget: "list"
        fields:
          - {label: Image, name: image, widget: image}
  - name: "education" # Used in routes, e.g., /admin/collections/blog
    label: "Education" # Used in the UI
    folder: "content/education" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "hatchery" # Used in routes, e.g., /admin/collections/blog
    label: "Hatchery" # Used in the UI
    folder: "content/hatchery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "birds" # Used in routes, e.g., /admin/collections/blog
    label: "Birds" # Used in the UI
    folder: "content/animals" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    filter: {field: "category", value: "birds"}
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Scientific Name", name: "scientific_name", widget: "string"}
      - {label: "Distribution", name: "distribution", widget: "string"}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Lifespan", name: "lifespan", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "hidden", default: "birds"}
  - name: "invertebrates" # Used in routes, e.g., /admin/collections/blog
    label: "Invertebrates" # Used in the UI
    folder: "content/animals" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    filter: {field: "category", value: "invertebrates"}
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Scientific Name", name: "scientific_name", widget: "string"}
      - {label: "Distribution", name: "distribution", widget: "string"}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Lifespan", name: "lifespan", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "hidden", default: "invertebrates"}
  - name: "mammals" # Used in routes, e.g., /admin/collections/blog
    label: "Mammals" # Used in the UI
    folder: "content/animals" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    filter: {field: "category", value: "mammals"}
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Scientific Name", name: "scientific_name", widget: "string"}
      - {label: "Distribution", name: "distribution", widget: "string"}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Lifespan", name: "lifespan", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "hidden", default: "mammals"}
  - name: "fish" # Used in routes, e.g., /admin/collections/blog
    label: "Fish" # Used in the UI
    folder: "content/animals" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    filter: {field: "category", value: "fish"}
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Scientific Name", name: "scientific_name", widget: "string"}
      - {label: "Distribution", name: "distribution", widget: "string"}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Lifespan", name: "lifespan", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "hidden", default: "fish"}
  - name: "salmon" # Used in routes, e.g., /admin/collections/blog
    label: "Salmon" # Used in the UI
    folder: "content/animals" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    filter: {field: "category", value: "salmon"}
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Scientific Name", name: "scientific_name", widget: "string"}
      - {label: "Distribution", name: "distribution", widget: "string"}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Lifespan", name: "lifespan", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "hidden", default: "salmon"}
